force-app/main/default/objects/Imoveis__c/Imoveis__c.object-meta.xml
<CustomObject>
    <description>Exibe informaçoes de imóveis</description>
    <label>Imóveis</label>
    <nameField>
        <displayFormat>IMO - {0000}</displayFormat>
        <label>Nome de Imoveis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imoveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imoveis__c/fields/Copa__c.field-meta.xml
<CustomField>
    <fullName>Copa__c</fullName>
    <inlineHelpText>Insira a quantidade de Copas</inlineHelpText>
    <label>Copa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Cozinha__c.field-meta.xml
<CustomField>
    <fullName>Cozinha__c</fullName>
    <inlineHelpText>Insira a quantidade de Cozinha</inlineHelpText>
    <label>Cozinha</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Finalidade_do_Imovel__c.field-meta.xml
<CustomField>
    <fullName>Finalidade_do_Imovel__c</fullName>
    <inlineHelpText>Escolha o tipo da finalidade do imovel</inlineHelpText>
    <label>Finalidade do Imovel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nenhum</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Garagem__c.field-meta.xml
<CustomField>
    <fullName>Garagem__c</fullName>
    <inlineHelpText>Insira a quantidade de Garagem</inlineHelpText>
    <label>Garagem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Mobiliado__c.field-meta.xml
<CustomField>
    <fullName>Mobiliado__c</fullName>
    <description>possui mobilia no imovel</description>
    <inlineHelpText>Escolha se o imovel é mobiliado</inlineHelpText>
    <label>Mobiliado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escolha</fullName>
                <default>true</default>
                <label>Escolha</label>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Quartos__c.field-meta.xml
<CustomField>
    <fullName>Quartos__c</fullName>
    <inlineHelpText>Insira quantidade de quartos</inlineHelpText>
    <label>Quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <inlineHelpText>Insira a quantidade de Salas</inlineHelpText>
    <label>Sala</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Imovel esta disponivel ou nao</description>
    <inlineHelpText>Escolha disponibilidade do imovel</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nenhum</fullName>
                <default>true</default>
                <label>Nenhum</label>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>Indisponivel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <inlineHelpText>Insira a quantidade de Suites</inlineHelpText>
    <label>Suite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/TipoImovel__c.field-meta.xml
<CustomField>
    <fullName>TipoImovel__c</fullName>
    <inlineHelpText>Escolha o Tipo do Imóvel</inlineHelpText>
    <label>Tipo de Imóvel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Apartamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Tipos_Comerciais__c.field-meta.xml
<CustomField>
    <fullName>Tipos_Comerciais__c</fullName>
    <inlineHelpText>Escolha um tipo comercial para o imovel com finalidade comercial</inlineHelpText>
    <label>Tipos Comerciais</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Finalidade_do_Imovel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nenhum</fullName>
            </value>
            <value>
                <fullName>Lojas de autopeças</fullName>
            </value>
            <value>
                <fullName>Farmcia</fullName>
            </value>
            <value>
                <fullName>Igreja</fullName>
            </value>
            <value>
                <fullName>Oficina Mecanica</fullName>
            </value>
            <value>
                <fullName>Galpão</fullName>
            </value>
            <value>
                <fullName>Fabrica</fullName>
            </value>
            <value>
                <fullName>Salão de beleza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Insira o valor imóvel</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ImobiliariaController.cls
public class ImobiliariaController {
    
    //Definiçoes das variaveis
    public integer quartos {get; set;} // é a interaçao das variaveis da pagina visual force com o banco de dados, get e set é recebe e enviar as informaçoes
    public integer Banheiros {get; set;}
    public integer Sala {get; set;}
    public integer Cozinha {get; set;}
    public integer Copa {get; set;}
    public integer Suite {get; set;}
    public integer garagem {get; set;}
    public integer Valor {get; set;}
    Public string  tipoImovel {get; set;}
    Public string Mobiliado {get; set;}
    Public string Status {get; set;}
    Public string FinalidadeImovel {get; set;} 
    Public string TiposComerciais {get; set;}
    
    //Método picklist     
    public List<SelectOption> getMinhasOpcoes(){
        
        //Mapear o campo de lista de seleção/picklist que desejo listar    
        Schema.DescribeFieldResult describeResult = Imoveis__c.TipoImovel__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption       
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
            
        }
        //Retorna a lista de selectOption criamos na variável de retorno
        return optionsToReturn;     
        
    }       
    
    //Método picklist adicionar segunda  opção 
    public List<SelectOption> getMinhasOpcoes2(){ //nao pode ter a mesma variavel para difeerentes picklist porisso coloquei a variavel com o "2" no final.  
        
        //Mapear o campo de lista de seleção/picklist que desejo listar    
        Schema.DescribeFieldResult describeResult = Imoveis__c.Mobiliado__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption       
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
            
        }
        //Retorna a lista de selectOption criamos na variável de retorno
        return optionsToReturn;     
        
    }       
    
    //Método picklist adicionar terceira  opção 
    public List<SelectOption> getMinhasOpcoes3(){ //nao pode ter a mesma variavel para difeerentes picklist porisso coloquei a variavel com o "3" no final.  
        
        //Mapear o campo de lista de seleção/picklist que desejo listar    
        Schema.DescribeFieldResult describeResult = Imoveis__c.Status__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption       
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
            
        }
        //Retorna a lista de selectOption criamos na variável de retorno
        return optionsToReturn;     
        
    }
    
    //Método picklist adicionar quarta opção 
    public List<SelectOption> getMinhasOpcoes4(){ //nao pode ter a mesma variavel para difeerentes picklist porisso coloquei a variavel com o "4" no final.  
        
        //Mapear o campo de lista de seleção/picklist que desejo listar    
        Schema.DescribeFieldResult describeResult = Imoveis__c.Finalidade_do_Imovel__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption       
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
            
        }
        //Retorna a lista de selectOption criamos na variável de retorno
        return optionsToReturn;     
        
    }
    
    //Método picklist adicionar quinta opção 
    public List<SelectOption> getMinhasOpcoes5(){ //nao pode ter a mesma variavel para difeerentes picklist porisso coloquei a variavel com o "5" no final.  
        
        //Mapear o campo de lista de seleção/picklist que desejo listar    
        Schema.DescribeFieldResult describeResult = Imoveis__c.Tipos_Comerciais__c.getDescribe();
        
        //listar as opções válidas dentro do meu campo
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        //Cria variável de retorno do tipo de lista para o objeto SelectOption       
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        //Adiciona as opções do campo listadas
        for(Schema.PicklistEntry pEntry : entries){
            
            //se a opção esta ativa
            //Ou pode aplicar o filtro que quiser, caso não queira mostrar todas as opções
            if(pEntry.isActive()){
                //Adiciona o nome e o valor na variável retorno
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
            
        }
        //Retorna a lista de selectOption criamos na variável de retorno
        return optionsToReturn;     
        
    }
    
    
    
    //Metodo salvar
    public void salvarImoveis(){
        Imoveis__c objImoveis = new Imoveis__c(); // objeto do tipo Imoveis, essa variavel ja é o que foi criado la dentro do salesforce quando inciei o projeto antes de codar
        objImoveis.Quartos__c = quartos;  // para fazer a integraçao de salvar tenho que puxar as variaveis que exites na visual force pagina e igualar a variavel.    
        objImoveis.Sala__c = Sala;
        objImoveis.Cozinha__c = Cozinha;
        objImoveis.Copa__c = Copa;
        objImoveis.Suite__c = Suite;
        objImoveis.Garagem__c = garagem;
        objImoveis.Valor__c = Valor;
        objImoveis.TipoImovel__c = TipoImovel;
        objImoveis.Mobiliado__c = Mobiliado;
        objImoveis.Status__c = Status;
        objImoveis.Finalidade_do_Imovel__c= FinalidadeImovel;
        objImoveis.Tipos_Comerciais__c = TiposComerciais;
        
        Try{
            
            if(objImoveis.TipoImovel__c == 'Nenhum' || objImoveis.TipoImovel__c == null){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'o campo tipo do imóvel dever ser preenchido!'));
                
                return;
            }
            
            if( objImoveis.Mobiliado__c == 'Escolha' || objImoveis.Mobiliado__c == null){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'o campo mobiliado dever ser preenchido!'));
                
                return;
            }
            if( objImoveis.Status__c == 'Nenhum' || objImoveis.Status__c == null){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'o campo status dever ser preenchido!'));
                
                return;
            }
            if( objImoveis.Finalidade_do_Imovel__c == 'Nenhum' || objImoveis.Finalidade_do_Imovel__c == null){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'o campo Tipos Comerciais dever ser preenchido!'));
                
                return;
            }
            if( objImoveis.Tipos_Comerciais__c == 'Nenhum' || objImoveis.Tipos_Comerciais__c == null){
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'o campo Tipos Comerciais dever ser preenchido!'));
                
                return;
            }
            
            Insert objImoveis; 
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.CONFIRM,'Imóvel cadastrado com sucesso!'));
            // Limpa os campos apos SALVAR 
            quartos = null;
            Banheiros = null;
            Sala = null;
            Cozinha = null;
            Copa = null;
            Suite = null;
            garagem = null;
            Valor = null;
            tipoImovel = null;
            Mobiliado= null;
            Status= null;
            FinalidadeImovel = null;
            TiposComerciais = null;
            
        }catch(DmlException e){
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'Por favor verifique todos os campos antes de salvar!'));
            
        }
    }
}